/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#fb5151",
        "on-background": "#2c2f30",
        "on-tertiary-fixed-variant": "#665500",
        "tertiary": "#6c5a00",
        "background": "#f5f6f7",
        "secondary-dim": "#902e02",
        "primary-container": "#6af2de",
        "on-tertiary-container": "#5b4b00",
        "on-surface-variant": "#595c5d",
        "on-tertiary-fixed": "#453900",
        "on-primary": "#c0fff3",
        "on-primary-container": "#00594f",
        "on-primary-fixed": "#00443c",
        "surface-container-low": "#eff1f2",
        "surface-tint": "#00675d",
        "inverse-surface": "#0c0f10",
        "on-secondary-container": "#832800",
        "secondary-fixed-dim": "#ffb196",
        "surface-bright": "#f5f6f7",
        "primary-fixed": "#6af2de",
        "tertiary-fixed-dim": "#efc900",
        "error-dim": "#9f0519",
        "on-tertiary": "#fff2cd",
        "surface-dim": "#d1d5d7",
        "on-primary-fixed-variant": "#006359",
        "surface": "#f5f6f7",
        "error": "#b31b25",
        "secondary-fixed": "#ffc4b1",
        "tertiary-dim": "#5e4e00",
        "outline-variant": "#abadae",
        "on-secondary-fixed-variant": "#922f03",
        "on-error": "#ffefee",
        "surface-container-high": "#e0e3e4",
        "inverse-primary": "#6df5e1",
        "surface-container-highest": "#dadddf",
        "on-secondary": "#ffefeb",
        "primary": "#00675d",
        "tertiary-fixed": "#ffd709",
        "tertiary-container": "#ffd709",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#ffc4b1",
        "outline": "#757778",
        "surface-container": "#e6e8ea",
        "inverse-on-surface": "#9b9d9e",
        "primary-dim": "#005a50",
        "surface-variant": "#dadddf",
        "on-error-container": "#570008",
        "primary-fixed-dim": "#5ae4d0",
        "on-secondary-fixed": "#621c00",
        "on-surface": "#2c2f30",
        "secondary": "#a03a0f"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Plus Jakarta Sans"],
        "label": ["Plus Jakarta Sans"]
      }
    },
  },
  plugins: [],
}
